language: python
sudo: false

addons:
  apt_packages:
      - pandoc
env:
  global:
    - GH_REF: github.com/scikit-beam/scikit-beam.git
    - secure: "A5gJ+qdPuf8BNUNkFC0XzMZaKAgDIQWwVoHGOslXFgjLvtluk0XOPWUqKhXf0jAII/pf40nGGo55wqNKpimhAO8oUBBeP9wM9JPf7l0KaZlAfzdDBdXDa2iwAdtiviAF54uJ7MvTzslCjcER+I8iJZUQylowDJ5fEe+yvLqOfy4="

python:
  # - 2.7
  # - 3.4
  - 3.5

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  # - conda config --set always_yes true
  # - conda update conda
  # - conda config --add channels scikit-xray
  # - conda create -n testenv pip nose python=$TRAVIS_PYTHON_VERSION numpy scipy scikit-image six coverage cython xraylib lmfit=0.8.3 netcdf4
  # - source activate testenv
  # # need to build_ext -i for the tests so that the .so is local to the source
  # # code.  We could also setup.py develop, but I'm not sure if that is any
  # # better
  # - python setup.py install build_ext -i
  # - pip install coveralls
  # - pip install codecov

script:
  - echo 'script'
  # - python run_tests.py

after_success:
  # - coveralls
  # - codecov
  - echo "GH_TOKEN=${GH_TOKEN}"
  - env
  - if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PYTHON_VERSION == 3.5 ]; then
      conda create -n docs_env python=$TRAVIS_PYTHON_VERSION sphinx numpydoc ipython jupyter pip matplotlib --yes;
      source activate docs_env;
      pip install sphinx_bootstrap_theme;
      cd ..;
      git clone https://github.com/scikit-beam/scikit-beam-examples.git;
      cd scikit-beam/doc;
      chmod +x deploy.sh;
      ./deploy.sh;
    fi;